---
version: 1.0
root: "./.tests/cloud_test/"
timeout: 7200  # 2 hour total total timeout
import:
  - .cloudtest/packet.yaml
  - .cloudtest/gke.yaml
  - .cloudtest/kind.yaml
  - .cloudtest/vagrant.yaml
  - .cloudtest/aws.yaml
  - .cloudtest/azure.yaml

retest:  # Allow to do test re-run if some kind of failures are detected, line CNI network plugin errors.
  count: 5  # Allow 5 times to do restart
  warmup-time: 15  # Put 15 seconds warmup for cluster instance to be used again.
  allowed-retests: 2  # If cluster instance have few attempts with retest requests one after another, we need to restart cluster.
  pattern:
    - "NetworkPlugin cni failed to set up pod"    # Error in AWS dur to leak of IPs or not ability to assign them.
    - "etcdserver: request timed out, possibly due to previous leader fail"  # Error in any could, reason unknown.
    - "unable to establish connection to VPP (VPP API socket file /run/vpp/api.sock does not exist)"  # a VPP is not started, it will be re-started in general, but will cause test fail.
reporting:
  junit-report: "results/junit.xml"
health-check:
  - message: "Branch is not up to date"
    interval: 60
    run: |
      ./.circleci/check_repo_uptodated.sh
executions:
  - name: "Test suite with default nsm"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - NSM_NAMESPACE=nsm-system
      - FIXED_NAMESPACE=true
    root: ./test/integration
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG
    timeout: 300
    source:
      tags:
        - single_cluster_suite
    after-all: |
      make k8s-delete-nsm-namespaces
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Recover test suite"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - NSM_NAMESPACE=nsm-system
      - FIXED_NAMESPACE=true
    root: ./test/integration
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG
    timeout: 300
    source:
      tags:
        - recover_suite
    after-all: |
      make k8s-delete-nsm-namespaces
    on-test-fail: |
      make k8s-delete-nsm-namespaces
      make helm-install-nsm
  - name: "Single cluster tests"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - NSM_NAMESPACE=nsm-system
    source:
      tags:
        - basic
        - recover
        - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Benchmark tests"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
    tags:
      - bench
    root: ./test/integration
    timeout: 600
    cluster-count: 1
    cluster-selector:
      - packet
    kubernetes-env:
      - KUBECONFIG
    on-test-fail: |
      make k8s-delete-nsm-namespaces

  - name: "Interdomain tests packet-aws"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
    source:
      tags:
        - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - packet
      - aws
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests gke-packet"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - gke
      - packet
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests azure-gke"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - azure
      - gke
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain tests aws-azure"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
    tags:
      - interdomain
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - aws
      - azure
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain suite tests packet-aws"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - FIXED_NAMESPACE=true
    source:
      tags:
        - interdomain
    after-all: |
      make k8s-delete-nsm-namespaces
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - packet
      - aws
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain suite tests gke-packet"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - FIXED_NAMESPACE=true
    source:
      tags:
        - interdomain_suite
    root: ./test/integration
    after-all: |
      make k8s-delete-nsm-namespaces
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - gke
      - packet
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain suite tests azure-gke"
    env:
      - STORE_POD_LOGS_IN_FILES=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - FIXED_NAMESPACE=true
    source:
      tags:
        - interdomain_suite
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - azure
      - gke
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    after-all: |
      make k8s-delete-nsm-namespaces
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Interdomain suite tests aws-azure"
    env:
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)
      - FIXED_NAMESPACE=true
    source:
      tags:
        - interdomain_suite
    root: ./test/integration
    timeout: 600
    cluster-count: 2
    cluster-selector:
      - aws
      - azure
    kubernetes-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
    after-all: |
      make k8s-delete-nsm-namespaces
    on-test-fail: |
      make k8s-delete-nsm-namespaces
  - name: "Example-helm-vpn"
    kind: shell
    timeout: 300
    env:
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)/vpn-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      scripts/helm-test-charts.sh nsm admission-webhook vpn
    on-test-fail: |
      make k8s-delete-nsm-namespaces

  - name: "Example-helm-icmp"
    kind: shell
    timeout: 300
    env:
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)/icmp-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      scripts/helm-test-charts.sh nsm admission-webhook icmp-responder
    on-test-fail: |
      make k8s-delete-nsm-namespaces

  - name: "Example-helm-icmp kernel-forwarder"
    kind: shell
    timeout: 300
    env:
      - FORWARDING_PLANE=kernel
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)/icmp-example
      - SPIRE_ENABLED=false  # because spire is already installed
    kubernetes-env:
      - KUBECONFIG
    run: |
      scripts/helm-test-charts.sh nsm admission-webhook icmp-responder
    on-test-fail: |
      make k8s-delete-nsm-namespaces

  - name: "Example-helm-crossconnect-monitor"
    kind: shell
    timeout: 300
    env:
      - NSM_NAMESPACE=nsm-system
      - CLUSTER_RULES_PREFIX=null
      - ARCHIVE_ARTIFACTS=true
      - ARTIFACTS_DIR=/home/circleci/project/.tests/cloud_test/$(cluster-name)/$(test-name)/crossconnect-monitor-example
      - SPIRE_ENABLED=false  # because spire is already installed
      - CHECK_CMD=scripts/verify_crossconnect_monitor.sh
    kubernetes-env:
      - KUBECONFIG
    run: |
      scripts/helm-test-charts.sh nsm admission-webhook icmp-responder crossconnect-monitor
    on-test-fail: |
      make k8s-delete-nsm-namespaces
