version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
import:
  - .cloudtest/packet.yaml
  - .cloudtest/gke.yaml
  - .cloudtest/kind.yaml
  - .cloudtest/vagrant.yaml
  - .cloudtest/aws.yaml
  - .cloudtest/azure.yaml

reporting:
  junit-report: "results/junit.xml"
executions:
  - name: "Single cluster tests"
    tags:
      - tag
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    env:
      - WRITE_POD_LOGS_IN_FILES=true
      - WRITE_POD_LOGS_IN_DIR=./.tests/cloud_test/$(cluster-name)/logs
    kubernetes-env:
      - KUBECONFIG
#TODO restore config after testing
